#!/bin/bash

set -e

while getopts s:p:f: option
do
    case "${option}" in
        s) SERVERLESS_TPL="${OPTARG}";;
        p) PASSTHROUGH_TPL="${OPTARG}";;
        f) FUNC_NAME="${OPTARG}";;
    esac
done

./scripts/build-serverless -s "${SERVERLESS_TPL:-serverless.yml.tpl}" \
                           -p "${PASSTHROUGH_TPL:-templates/passthrough.json}" \
                           -f "${FUNC_NAME:-getTile}"

./sbt clean
./sbt assembly

if [ -f .serverless/lambda-geotrellis-tile-server.zip ]; then
    rm .serverless/lambda-geotrellis-tile-server.zip
fi

serverless deploy

rm serverless.yml
